const backsteps = [
  {
    id: 1,

    title: "Internet Fundementals",
    desc: "Understand how computer works",
    imgURL: "../../../images/badge.png",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 2,
    title: "Basic Frontend Knowledge",
    imgURL: "../../../images/frontend.png",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 3,

    title: "OS and General Information",
    imgURL:
      "../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 4,
    title: "Language: JavaScript",
    imgURL:"../../../images/setting.jpg",   
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 5,
    title: "Language Options : Java / C# / PHP / Rust / Go / Python / Ruby ",
    imgURL:"../../../images/setting.jpg",   
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 6,
    title: "Version Control Systems - Github",
    imgURL:"../../../images/setting.jpg",   
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 7,
    title: "Relational Database",
    imgURL:"../../../images/setting.jpg",   
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 8,
    title: "NoSQL Database",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 9,
    title: "Advanced Database",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 10,
    title: "APIs",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 11,
    title: "Web Security",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 12,
    title: "CI / CD",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 13,
    title: "Deisgn and Development Principles",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 14,
    title: "Search Engines",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 15,
    title: "Message Brokers",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 16,
    title: "Web Sockets",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 17,
    title: "Web Servers",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
  {
    id: 18,
    title: "Keep Learning",
    imgURL:"../../../images/setting.jpg",
    course: "Lorem Ipsum",
    mentor: "Lorem Ipsum",
    student: "Lorem",
  },
];

export default backsteps;
