const steps = [
  {
    id: "step1",
    title: "Internet Fundementals",
    desc: "Understand how computer works",
    imgURL: "../../../../images/badge.png",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step2",
    title: "HTML",
    imgURL: "../../../images/html.png",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step3",
    title: "CSS",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step4",
    title: "JavaScript Fundementals",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step5",
    title: "JavaScript Advanced",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step6",

    title: "Version Control Systems - Github",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step7",

    title: "Web Security Knowledge",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step8",

    title: "Package Managers",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step9",

    title: "Build Tools",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step10",

    title: "Frameworks - Modern CSS",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step11",

    title: "Frameworks - React.js",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step12",

    title: "Frameworks - Angular",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step13",
    title: "Frameworks - Vue.js",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step14",
    title: "GraphQL Server",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step15",
    title: "Static Site Generator",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step16",
    title: "Mobile Application",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step17",
    title: "Desktop Application",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
  {
    id: "step18",
    title: "Keep Learning",
    imgURL: "../../../images/setting.jpg",
    course: "Recomended Course",
    mentor: "Recommended Mentor",
    student: "Meet students who take same course as this",
  },
];

export default steps;
